# ========= Copyright 2025-2026 @ Eigent.ai All Rights Reserved. =========
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========= Copyright 2025-2026 @ Eigent.ai All Rights Reserved. =========

"""feat-trigger

Revision ID: 9464b9d89de7
Revises: add_timestamp_to_chat_step
Create Date: 2026-02-06 04:40:17.623286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from app.shared.types.trigger_types import ExecutionStatus
from app.shared.types.trigger_types import ExecutionType
from app.shared.types.trigger_types import ListenerType
from app.shared.types.trigger_types import RequestType
from app.shared.types.trigger_types import TriggerStatus
from app.shared.types.trigger_types import TriggerType
from sqlalchemy_utils.types import ChoiceType

# revision identifiers, used by Alembic.
revision: str = '9464b9d89de7'
down_revision: Union[str, None] = 'add_timestamp_to_chat_step'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trigger',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('trigger_type', ChoiceType(choices=TriggerType, impl=sa.String()), nullable=True),
    sa.Column('status', ChoiceType(choices=TriggerStatus, impl=sa.String()), nullable=True),
    sa.Column('webhook_url', sa.String(length=1024), nullable=True),
    sa.Column('webhook_method', ChoiceType(choices=RequestType, impl=sa.String()), nullable=True),
    sa.Column('custom_cron_expression', sa.String(length=100), nullable=True),
    sa.Column('listener_type', ChoiceType(choices=ListenerType, impl=sa.String()), nullable=True),
    sa.Column('agent_model', sa.String(length=100), nullable=True),
    sa.Column('task_prompt', sqlmodel.sql.sqltypes.AutoString(length=1500), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('max_executions_per_hour', sa.Integer(), nullable=True),
    sa.Column('max_executions_per_day', sa.Integer(), nullable=True),
    sa.Column('is_single_execution', sa.Boolean(), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_execution_status', sa.String(length=50), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('auto_disabled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_next_run_at'), 'trigger', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_trigger_project_id'), 'trigger', ['project_id'], unique=False)
    op.create_index(op.f('ix_trigger_user_id'), 'trigger', ['user_id'], unique=False)
    op.create_table('trigger_execution',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('execution_type', ChoiceType(choices=ExecutionType, impl=sa.String()), nullable=True),
    sa.Column('status', ChoiceType(choices=ExecutionStatus, impl=sa.String()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('tools_executed', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['trigger_id'], ['trigger.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_execution_execution_id'), 'trigger_execution', ['execution_id'], unique=True)
    op.create_index(op.f('ix_trigger_execution_trigger_id'), 'trigger_execution', ['trigger_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trigger_execution_trigger_id'), table_name='trigger_execution')
    op.drop_index(op.f('ix_trigger_execution_execution_id'), table_name='trigger_execution')
    op.drop_table('trigger_execution')
    op.drop_index(op.f('ix_trigger_user_id'), table_name='trigger')
    op.drop_index(op.f('ix_trigger_project_id'), table_name='trigger')
    op.drop_index(op.f('ix_trigger_next_run_at'), table_name='trigger')
    op.drop_table('trigger')
    # ### end Alembic commands ###
